Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-09, with the labels that each got.

#324 [#322] [Feature] 필터 기능 mysql 연결
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/FilterStudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPasswordAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPasswordFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindUpdatePasswordFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPasswordViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneSocialFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePasswordViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FavoriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudySearchAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/BottomNaviViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/FavoriteViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudySearchViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/adapter/WritePagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/BottomSheetWriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/CustomDialogWriteIntroExample.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/IndentLeadingMarginSpan.kt
  app/src/main/java/kr/co/lion/modigm/util/FilterSort.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/layout/fragment_filter_sort.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_my.xml
  app/src/main/res/layout/fragment_study_search.xml
Labels: 버그, 기능, UI, 리팩터링

#326 [#325] 파이어베이스 인증 계정이 삭제되는 버그 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
Labels: 버그

#329 [#328] 관심분야 enum class Interest로 변경 및 InterestList 파일 삭제
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/InterestList.kt
Labels: 리팩터링

#330 [#327] [Refactor] 필터 및 스터디 목록 리팩토링
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/FavoriteData.kt
  app/src/main/java/kr/co/lion/modigm/model/FilterStudyData.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyMemberData.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyTechStackData.kt
  app/src/main/java/kr/co/lion/modigm/model/TechStackData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudySearchViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_field.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_proceed.xml
  app/src/main/res/layout/fragment_write_skill.xml
Labels: UI, 리팩터링

#333 [feature #308] 스터디 신청 알림 설정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDao.kt
  app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/NotificationData.kt
  app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/NotificationRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/FCMService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/vm/NotificationViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/drawable/icon_notifications_24px.xml
  app/src/main/res/drawable/icon_sync_24px.xml
  app/src/main/res/drawable/red_dot.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/row_notification.xml
  app/src/main/res/menu/menu_chat_toolbar.xml
  app/src/main/res/menu/menu_notification_toolbar.xml
  app/src/main/res/menu/menu_study_bottom_navi.xml
Labels: 기능, UI

#334 [#331] [Refactor] 글작성 파트 코드 정리 및 이미지 저장 개선
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/WriteRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/WriteStudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/CustomLoginErrorDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FavoriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/CustomCancelDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/CustomWriteErrorDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/OnTechStackSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/TechStackBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteTechStackFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteTypeFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/res/layout/fragment_tech_stack_bottom_sheet.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_field.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_proceed.xml
  app/src/main/res/layout/fragment_write_skill.xml
  app/src/main/res/layout/fragment_write_tech_stack.xml
  app/src/main/res/layout/fragment_write_type.xml
  app/src/main/res/layout/row_study.xml
  app/src/main/res/values/strings.xml
Labels: 기능, UI, 리팩터링

#339 [#336] feature 신고하기 기능 구글폼과 연결
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
Labels: 기능

#341 [#337] feature 회원가입 기능 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinCompleteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/res/layout/fragment_join_complete.xml
  app/src/main/res/raw/join_complete_animation.json
Labels: 기능

#343 [fix #342] 알림 기능 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/CustomNotificationPermissionDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/FCMService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/vm/NotificationViewModel.kt
  app/src/main/res/layout/custom_dialog_notification_permission.xml
  app/src/main/res/layout/fragment_notification.xml
Labels: 버그, 기능, 리팩터링

#346 [#340] [Fix] 테스트 피드백 사항 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/WriteRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudySearchViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/CustomIntroDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/KeyBoardUtil.kt
  app/src/main/java/kr/co/lion/modigm/util/Picture.kt
  app/src/main/java/kr/co/lion/modigm/util/StudyPlace.kt
  app/src/main/java/kr/co/lion/modigm/util/study/FilterSort.kt
  app/src/main/java/kr/co/lion/modigm/util/study/StudyOnOffline.kt
  app/src/main/java/kr/co/lion/modigm/util/study/StudyType.kt
  app/src/main/res/drawable/ic_modigm_foreground.xml
  app/src/main/res/layout/custom_popup_cover_image.xml
  app/src/main/res/layout/fragment_other_login.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_proceed.xml
  app/src/main/res/layout/fragment_write_tech_stack.xml
  app/src/main/res/layout/fragment_write_type.xml
  app/src/main/res/menu/menu_study_bottom_navi.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modigm.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modigm_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modiigm.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modiigm_round.xml
  app/src/main/res/mipmap-hdpi/ic_modigm.webp
  app/src/main/res/mipmap-hdpi/ic_modigm_round.webp
  app/src/main/res/mipmap-mdpi/ic_modigm.webp
  app/src/main/res/mipmap-mdpi/ic_modigm_round.webp
  app/src/main/res/mipmap-xhdpi/ic_modigm.webp
  app/src/main/res/mipmap-xhdpi/ic_modigm_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_modigm.webp
  app/src/main/res/mipmap-xxhdpi/ic_modigm_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_modigm.webp
  app/src/main/res/mipmap-xxxhdpi/ic_modigm_round.webp
  app/src/main/res/values/ic_modigm_background.xml
  gradle/libs.versions.toml
Labels: 기능, UI, 리팩터링

#348 [#335] bug sns 계정 회원가입 시 전화번호 통합이 안되는 버그
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
Labels: 버그

#349 #338 feature: 프로필 화면 1차 테스트 피드백 적용
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfilepicBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/res/layout/custom_profilepic_dropdown.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 버그

#352 [#345] feature 이메일 인증 기능 추가
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinEmailVerificationFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep1ViewModel.kt
  app/src/main/res/layout/fragment_join_email_verification.xml
  app/src/main/res/raw/auth_email_send_animation.json
Labels: 기능

#353 #350 feature: 로그아웃 시 광고 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/popup/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/popup/LogoutAdDialog.kt
  app/src/main/res/layout/custom_dialog_logout_ad.xml
  gradle/libs.versions.toml
Labels: 기능, UI

#354 #351 fix: 프로필 수정 시 오류
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfilepicBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/res/layout/custom_profile_report_dropdown.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profilepic_bottom_sheet.xml
Labels: 버그, 기능, UI

#359 [#356] feature userdata 회원가입 일자 속성 추가
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 기능

#360 [Fix #344] 글 상세 기능 수정
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Skill.kt
  app/src/main/res/drawable/custom_back_icon.xml
  app/src/main/res/drawable/icon_googleforms.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_edit.xml
  app/src/main/res/layout/fragment_skill_bottom_sheet.xml
  app/src/main/res/layout/row_detail_join_member.xml
Labels: 버그, 기능, UI

#363 [#362] feat userJoinDate 타입을 LocalDateTime으로 변경
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
Labels: 기능

#368 [Fix] #366 회원가입 insertUserData 메서드 수정
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
Labels: 버그

#373 [fix #367] 이미지 업로드 s3로 변경, 스터디 커버 사진 변경시 기존 이미지 s3에서 삭제
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
Labels: 버그, 기능

#371 [Design] #369 회원가입 시 이름 입력 안내문구 추가
  app/src/main/res/layout/fragment_join_step2.xml
Labels: UI

#379 [#370] feature 회원 탈퇴 기능 추가
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/DeleteUserFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/DeleteUserViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/drawable/icon_person_remove_24.xml
  app/src/main/res/layout/fragment_delete_user.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: 기능

#380 [feature #374] 2차 테스트 피드백 수정
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDao.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDao.kt
  app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/NotificationRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/vm/NotificationViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/popup/LogoutAdDialog.kt
  app/src/main/java/kr/co/lion/modigm/util/Skill.kt
  app/src/main/res/layout/fragment_detail_edit.xml
Labels: 버그, 기능
