Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-05, with the labels that each got.

#4 test
  app/build.gradle.kts
Labels: 기능, UI

#31 [#28] Feature 소셜로그인 화면 UI
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/res/drawable/background_login.jpg
  app/src/main/res/drawable/kakao_login_medium_wide.png
  app/src/main/res/drawable/logo_modigm.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_login2.xml
Labels: UI

#34 [#24] feature 회원 가입 UI 작업
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/adapter/JoinViewPagerAdapter.kt
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_step1.xml
  app/src/main/res/layout/fragment_join_step2.xml
  app/src/main/res/layout/fragment_join_step3.xml
Labels: 기능, UI

#33 [#23] feature - 채팅 UI 관련 추가
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/drawable/icon_add_24px.xml
  app/src/main/res/drawable/icon_arrow_up_24px.xml
  app/src/main/res/drawable/icon_back_24px.xml
  app/src/main/res/drawable/icon_more_vert_24px.xml
  app/src/main/res/drawable/icon_search_24px.xml
  app/src/main/res/drawable/style_button_send_gray_chatroom.xml
  app/src/main/res/drawable/style_edittext_chatroom.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_group.xml
  app/src/main/res/layout/fragment_chat_oneto_one.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/row_chatroom_filed.xml
  app/src/main/res/menu/menu_chat_toolbar.xml
  app/src/main/res/menu/menu_chatroom_toolbar.xml
  app/src/main/res/menu/popup_menu_chatroom_more_vert.xml
Labels: UI

#32 [#29] feature 스터디 글 작성 화면 UI
  App bar/1. Top/A. Regular/Arrow back.svg
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
  app/src/main/res/drawable/arrow_back_24px.xml
  app/src/main/res/drawable/tab_background.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_field.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_proceed.xml
  app/src/main/res/layout/fragment_write_skill.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: UI

#40 [#30] feature 스터디 글 작성 화면 탭분야
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/res/drawable/tab_background.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_field.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 기능, UI

#38 [Feature] #35 자체 로그인 화면 구현, Material 스타일로 전환
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
Labels: 기능, UI

#44 [Feature] #43 프래그먼트 전환
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
Labels: 기능

#42 [Feature] #37 채팅방 대화 내용 (UI, 기능)
  app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/res/drawable/style_message_received.xml
  app/src/main/res/drawable/style_message_sent.xml
  app/src/main/res/layout/fragment_chat_oneto_one.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/item_message_received.xml
  app/src/main/res/layout/item_message_sent.xml
Labels: 기능, UI

#47 [#46] Fix - Fragment 이동관련 및 xml 오류 해결
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/res/layout/fragment_other_login.xml
Labels: 기능, UI

#48 [#36] feature 회원 가입 입력 관련 기능 구현
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_step2.xml
  app/src/main/res/layout/fragment_join_step3.xml
Labels: 기능, UI

#53 [Feature #27] 글 상세보기 화면 UI
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/res/drawable/icon_arrow_back_24px.xml
  app/src/main/res/drawable/icon_clock_24px.xml
  app/src/main/res/drawable/icon_edit_24px.xml
  app/src/main/res/drawable/icon_error_24px.xml
  app/src/main/res/drawable/icon_expand_less_24px.xml
  app/src/main/res/drawable/icon_expand_more_24px.xml
  app/src/main/res/drawable/icon_favorite_24px.xml
  app/src/main/res/drawable/icon_favorite_full_24px.xml
  app/src/main/res/drawable/icon_group_24px.xml
  app/src/main/res/drawable/icon_location_on_24px.xml
  app/src/main/res/drawable/icon_send_plane_24px.xml
  app/src/main/res/drawable/icon_settings_24px.xml
  app/src/main/res/drawable/image_detail_1.jpg
  app/src/main/res/drawable/image_detail_2.jpg
  app/src/main/res/layout/custom_detail_popup_menu_item.xml
  app/src/main/res/layout/custom_detail_popup_menu_stateitem.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: 기능, UI

#52 [#45] feat - ChatRoom 채팅방, 대화내용 (Group, 1:1) 분리
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
Labels: 기능, UI

#56 [#49] feature 이미 가입한 계정 알림 화면 작업
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/adapter/JoinViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/drawable/kakaotalk_sharing_btn_small.png
  app/src/main/res/layout/fragment_join_duplicate.xml
Labels: 기능, UI

#61 [#54] feature 프로필, 검색 버튼 클릭 시 UI 추가
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/res/drawable/test_profile_image.jpg
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/item_message_received.xml
  app/src/main/res/layout/item_message_sent.xml
  app/src/main/res/menu/menu_chat_toolbar.xml
Labels: UI

#65 [Feature #55] 글 상세 멤버 목록 화면 구현
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/drawable/icon_check_24.xml
  app/src/main/res/drawable/icon_close_24.xml
  app/src/main/res/layout/custom_dialog.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_apply_member.xml
  app/src/main/res/layout/fragment_detail_join_member.xml
  app/src/main/res/layout/fragment_detail_member.xml
  app/src/main/res/layout/row_detail_apply_member.xml
  app/src/main/res/layout/row_detail_join_member.xml
Labels: 기능, UI

#68 [#64] feature 채팅 방 목록 관련 ViewModel, Model 추가 및 Firebase 연동
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatMessagesDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
Labels: 기능

#72 [#69] feature 채팅 메세지 model, viewmodel, dao 추가 및 firebase 연동작업
  app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatMessagesDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/KeyBoardUtil.kt
  app/src/main/res/color/bottom_navigation_selector_color.xml
  app/src/main/res/drawable/icon_chat_24px.xml
  app/src/main/res/drawable/icon_study_book_24px.xml
  app/src/main/res/drawable/test_profile_image_iu.jpg
  app/src/main/res/drawable/test_profile_image_ryu.jpeg
  app/src/main/res/drawable/test_profile_image_son.png
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_room.xml
Labels: 기능, 리팩터링

#70 [#59] feature 회원가입 ViewModel 구조 적용
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep1ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/res/layout/fragment_join_step1.xml
  app/src/main/res/layout/fragment_join_step2.xml
Labels: 기능, 리팩터링

#73 [#66] feature 모집 글 작성 탭진행방식
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/res/layout/fragment_write_proceed.xml
Labels: UI

#78 [#76] feature 모듈(앱 수준) Gradle 파일에 Firebase Authentication 종속 항목 추가
  app/build.gradle.kts
Labels: 기능

#82 [Feature #67] 글 상세 게시글 수정 화면 구현
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/layout/fragment_detail_edit.xml
  app/src/main/res/values/style.xml
Labels: 기능, UI

#84 [#77] feature - 채팅 하단 바 설정 및 채팅방 나가기 기능
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatViewModel.kt
  app/src/main/res/layout/fragment_chat.xml
Labels: 기능

#88 [#87] feature 모집 글 작성 탭기술
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
  app/src/main/res/layout/fragment_write_skill.xml
Labels: UI

#91 fix #90: google-services.json 변경
  app/google-services.json
Labels: 버그

#92 [#81] feature 스터디 목록 UI 데이터작업
  app/src/main/java/kr/co/lion/modigm/db/remote/StudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/layout/fragment_bottom_navi.xml
  app/src/main/res/layout/fragment_filter_sort.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_my.xml
Labels: 기능, UI

#94 [#89] feature 모집 글 작성 탭 - 소개
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/BottomSheetWriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/CustomDialogWriteIntroExample.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/IndentLeadingMarginSpan.kt
  app/src/main/res/drawable/icon_photo_plus_24px.xml
  app/src/main/res/drawable/style_custom_dialog_write_intro_example.xml
  app/src/main/res/layout/custom_dialog_write_intro_example.xml
  app/src/main/res/layout/fragment_bottom_sheet_write_proceed.xml
  app/src/main/res/layout/fragment_write_intro.xml
Labels: UI

#96 #80 feature: 프로필 화면 데이터베이스 연결하여 정보 불러오기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/datasource/UserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/model/UserInfoData.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/java/kr/co/lion/modigm/util/Interest.kt
  app/src/main/res/drawable/icon_facebook_logo.png
  app/src/main/res/drawable/icon_github_logo.png
  app/src/main/res/drawable/icon_instagram_logo.png
  app/src/main/res/drawable/icon_link.png
  app/src/main/res/drawable/icon_linkedin_logo.png
  app/src/main/res/drawable/icon_notion_logo.png
  app/src/main/res/drawable/icon_tistory_logo.png
  app/src/main/res/drawable/icon_twitter_logo.png
  app/src/main/res/drawable/icon_velog_logo.png
  app/src/main/res/drawable/icon_youtube_logo.png
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_web.xml
  app/src/main/res/layout/row_link.xml
Labels: 기능

#100 [#79] feature 회원가입 데이터 연동
  app/src/main/java/kr/co/lion/modigm/db/remote/JoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/InterestList.kt
  app/src/main/res/drawable/email_login_logo.png
Labels: 기능

#108 [#105] feature - 채팅 방 안 메뉴대화방 나가기 멤버 보기 공지사항
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt
  app/src/main/res/drawable/icon_menu_24px.xml
  app/src/main/res/drawable/icon_out_24px.xml
  app/src/main/res/drawable/icon_speaker_24px.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/row_chatroom_member.xml
  app/src/main/res/menu/menu_chatroom_toolbar.xml
  app/src/main/res/values/colors.xml
Labels: 기능, UI

#103 [Feature #83] 게시글 수정 화면 기술 선택 bottomsheet 구현
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnSkillSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/res/drawable/style_bottom_sheet_background.xml
  app/src/main/res/layout/fragment_skill_bottom_sheet.xml
Labels: 기능, UI

#111 [#106] feature 파이어베이스 전화번호 인증 에러 처리
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 버그, 리팩터링

#110 #99 feature: 프로필 화면의 스터디 목록 구성
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/util/Interest.kt
  app/src/main/java/kr/co/lion/modigm/util/StudyCategory.kt
  app/src/main/java/kr/co/lion/modigm/util/StudyPlace.kt
  app/src/main/res/drawable/icon_closed_book_24px.xml
  app/src/main/res/drawable/icon_code_box_24px.xml
  app/src/main/res/drawable/icon_study_book_24px.xml
  app/src/main/res/drawable/icon_trophy_24px.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/row_host_study.xml
Labels: 기능

#116 #115 feature: studydata 필드 이름 수정
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
Labels: 리팩터링

#112 [Feature #104] 게시글 수정 화면 장소 선택 bottomsheet 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/PlaceSearchResultsAdapter.kt
  app/src/main/res/drawable/icon_maps_location_24px.xml
  app/src/main/res/layout/fragment_detail_edit.xml
  app/src/main/res/layout/fragment_place_bottom_sheet.xml
  app/src/main/res/layout/fragment_skill_bottom_sheet.xml
  app/src/main/res/layout/row_place.xml
Labels: 기능, UI

#118 [#109] feature - 채팅 방 목록 검색기능
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
  app/src/main/res/layout/fragment_chat.xml
Labels: 기능, UI

#122 [#114] feature 이메일 sns 계정에 따른 회원가입 절차 분기
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
  app/src/main/res/layout/fragment_join_step1.xml
  app/src/main/res/layout/fragment_join_step2.xml
  app/src/main/res/layout/fragment_join_step3.xml
Labels: 기능

#120 [#107] Feature 스터디 목록과 로그인 화면 정리 로그인 api
  app/src/main/java/kr/co/lion/modigm/db/remote/StudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/res/animator/button_click.xml
  app/src/main/res/drawable/icon_key_24px.xml
  app/src/main/res/drawable/icon_mail_24px.xml
  app/src/main/res/drawable/kakao_login_large_wide.png
  app/src/main/res/font/one_mobile_pop_otf.otf
  app/src/main/res/font/one_mobile_pop_ttf.ttf
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
  app/src/main/res/layout/row_study_all.xml
Labels: 기능, UI, 리팩터링

#126 [Feature #113] 찜 화면 구현
  app/src/main/java/kr/co/lion/modigm/ui/like/LikeFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/like/adapter/LikeAdapter.kt
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/row_like.xml
Labels: 기능, UI
