Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-06, with the labels that each got.

#129 [Feature #127] 글 수정 화면 다이얼로그 연결 및 글 상세화면 삭제 다이얼로그 구현
  app/src/main/java/kr/co/lion/modigm/ui/detail/CustomIntroDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/res/layout/custom_dialog_intro_example.xml
  app/src/main/res/layout/fragment_detail_edit.xml
  app/src/main/res/layout/row_like.xml
Labels: 기능, UI, 리팩터링

#134 [Feature #132] 주소 선택 상세주소 추가
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_edit.xml
Labels: 기능, UI

#128 [#125] fix UI 모집 글 작성 UI 전체 수정 2
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
  app/src/main/res/drawable/icon_camera_24px.xml
  app/src/main/res/layout/custom_popup_menu_write_intro.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_skill.xml
  app/src/main/res/xml/file_path.xml
Labels: 기능, UI

#136 [#121] [Feature] 로그인 api 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
  app/src/main/res/layout/row_study_all.xml
  app/src/main/res/layout/row_study_my.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 기능, UI, 리팩터링

#137 [#123] feature 회원가입 기능 디버깅 및 리팩토링
  app/src/main/java/kr/co/lion/modigm/db/remote/JoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep1ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_duplicate.xml
  app/src/main/res/layout/fragment_join_step2.xml
Labels: 버그, 리팩터링

#142 [Feature #130] 글 상세화면 mvvm 및 repository 구조 적용
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Skill.kt
  app/src/main/res/drawable/icon_account_circle.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: 기능, UI, 리팩터링

#149 [Feature #148] 글 상세화면 mvvm 및 repository 구조 재 적용
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Skill.kt
  app/src/main/res/drawable/icon_account_circle.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: 기능, UI, 리팩터링

#143 [#139] [Feature] 스플래시 스크린 적용
  app/src/main/AndroidManifest.xml
  app/src/main/ic_modiigm-playstore.png
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/res/drawable/ic_modiigm_foreground.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modiigm.xml
  app/src/main/res/mipmap-anydpi-v26/ic_modiigm_round.xml
  app/src/main/res/mipmap-hdpi/ic_modiigm.webp
  app/src/main/res/mipmap-hdpi/ic_modiigm_round.webp
  app/src/main/res/mipmap-mdpi/ic_modiigm.webp
  app/src/main/res/mipmap-mdpi/ic_modiigm_round.webp
  app/src/main/res/mipmap-xhdpi/ic_modiigm.webp
  app/src/main/res/mipmap-xhdpi/ic_modiigm_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_modiigm.webp
  app/src/main/res/mipmap-xxhdpi/ic_modiigm_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_modiigm.webp
  app/src/main/res/mipmap-xxxhdpi/ic_modiigm_round.webp
  app/src/main/res/values/ic_modiigm_background.xml
Labels: 버그, 기능, UI, 리팩터링

#150 [#135] feature WriteFragment mvvm 구조 적용
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/more/BottomSheetWriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_field.xml
  app/src/main/res/layout/fragment_write_intro.xml
  app/src/main/res/layout/fragment_write_period.xml
  app/src/main/res/layout/fragment_write_proceed.xml
  app/src/main/res/layout/fragment_write_skill.xml
Labels: 리팩터링

#151 [#133] feature - 채팅 방 로그인 및 멤버 db 연동
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/ChatRoomRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatRoomViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/res/layout/row_chatroom_filed.xml
Labels: 기능

#152 [#138] feature sns 로그인 시 회원가입 진행
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_step2.xml
Labels: 기능

#156 [#155] feature 전화번호 중복 확인 기능 수정
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
  app/src/main/res/layout/fragment_join.xml
Labels: 버그, 리팩터링

#158 [#144] [Feature] 이메일 로그인 및 자동로그인
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/layout/fragment_find_email.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
Labels: 기능, UI, 리팩터링

#161 [#157] feature 회원가입 기능 디버깅
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 버그, 리팩터링

#165 [#164] [Feature] 스터디 목록 이미지 연동 및 신청 방식 표기 수정
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
  app/src/main/res/drawable/background_login2.jpg
  app/src/main/res/drawable/background_login3.jpg
  app/src/main/res/layout/fragment_login.xml
Labels: 기능, UI

#167 #141 feature: 프로필 수정 화면 구현
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAddAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAddViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/java/kr/co/lion/modigm/util/Interest.kt
  app/src/main/java/kr/co/lion/modigm/util/Picture.kt
  app/src/main/res/drawable/style_round_border.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_interest_bottom_sheet.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/row_link_add.xml
Labels: 기능, UI

#169 [Feature #145] 글 수정 화면 db 연결
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/OnSkillSelectedListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Skill.kt
  app/src/main/res/drawable/icon_camera_alt_24.xml
  app/src/main/res/layout/custom_popup_cover_image.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_detail_edit.xml
Labels: 기능, UI, 리팩터링

#172 [Feature #170] 멤버 목록 화면 구현
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/res/layout/row_detail_join_member.xml
Labels: 기능, UI, 리팩터링

#163 [#162] feature 이메일 계정 회원가입 후 로그인 페이지로 되돌아오기
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 버그, 기능

#171 [#153] feature - 채팅 관련 된 기능 firebase 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatMessagesDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/repository/ChatRoomRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatRoomViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/CameraUtil.kt
  app/src/main/res/drawable/base_profile_image.jpg
  app/src/main/res/drawable/base_profile_image2.png
  app/src/main/res/drawable/test_profile_image_iu.jpg
  app/src/main/res/drawable/test_profile_image_ryu.jpeg
  app/src/main/res/drawable/test_profile_image_son.png
  app/src/main/res/layout/item_message_received.xml
  app/src/main/res/layout/item_message_sent.xml
  app/src/main/res/layout/row_chatroom_filed.xml
  app/src/main/res/layout/row_chatroom_member.xml
Labels: 버그, 기능

#179 [#178] feat - DetailFragment - 채팅 방으로 입장하는 코드 추가
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
Labels: 기능

#181 [Fix] #180 회원 가입 시 이메일 데이터가 누락되는 부분 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 버그

#184 [#183] feature 핸드폰 번호 변경 기능
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/res/layout/fragment_change_phone.xml
Labels: 기능

#174 [Feature #173] 게시글 삭제처리
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
Labels: 기능, 리팩터링

#189 #168 feature: sharedpreference 적용
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Interest.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/anim/slide_in.xml
  app/src/main/res/anim/slide_out.xml
  app/src/main/res/layout/fragment_change_pw.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/row_host_study.xml
Labels: 기능, 리팩터링

#185 [#166] [Feature] 로그인처리 작업
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/KeyBoardUtil.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/drawable/icon_person_add_24px.xml
  app/src/main/res/drawable/login_snackbar_background.xml
  app/src/main/res/layout/custom_snackbar_with_icon.xml
  app/src/main/res/layout/custom_snackbar_without_icon.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
Labels: 기능, UI, 리팩터링

#191 [#177] feature - chat - 채팅 방 생성 기능 추가
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
Labels: 기능

#197 [#193] feature 전화 번호 변경 화면 수정
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/layout/fragment_change_phone.xml
Labels: 버그, UI

#200 [Feature] 스터디 신청하기 구현
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/NoMoveBehavior.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/like/LikeFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/like/adapter/LikeAdapter.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/row_detail_apply_member.xml
Labels: 기능, UI, 리팩터링

#199 [#190] fix db 연동 오류 수정
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
Labels: 버그, 기능

#201 [#194] feature - chatting data 데이터 처리 수정
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
Labels: 버그, 기능

#208 [#204] feature - 채팅 방 (멤버 등록 및 내보내기) 데이터 업데이트
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
Labels: 기능

#207 [#206] Fix 이름 입력 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/res/layout/fragment_join_step2.xml
Labels: 버그

#211 [Feature] 각 유저 프로필로 이동 연결
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
Labels: 기능

#213 [#212] Fix 뒤로가기 및 파이어베이스 인증 등록 정보 삭제 로직 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 버그

#220 [Feature] fab버튼 클릭 추가
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
Labels: 기능

#218 [#210] feature - 글 작성 시 채팅 방 생성 null 값 가져오는 오류
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
Labels: 버그, 기능

#217 [#209] feature 등록한 사진이 옆으로 생기도록 수정
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/res/layout/fragment_write_intro.xml
Labels: 기능, UI

#224 #205 fix: 프로필 수정 시 UI 업데이트
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
Labels: 버그, 기능

#226 [#223] feature 글 작성 db uid 첨부 & WriteFragment, WriteIntroFragment xml 파일 수정
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_intro.xml
Labels: 버그, UI

#227 [#222] feat - 채팅 방 1:1 채팅 방 생성 및 이동
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/repository/ChatRoomRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatRoomViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
Labels: 기능

#233 [#216] feature 이메일 찾기 기능
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/CustomFindEmailDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailAuthViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailViewModel.kt
  app/src/main/res/layout/fragment_find_email.xml
  app/src/main/res/layout/fragment_find_email_auth.xml
Labels: 기능

#235 [#232] feature 비밀번호 재설정 기능
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPwAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPwFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/ResetPwFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPwAuthViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPwViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/ResetPwViewModel.kt
  app/src/main/res/layout/fragment_find_pw.xml
  app/src/main/res/layout/fragment_find_pw_auth.xml
  app/src/main/res/layout/fragment_reset_pw.xml
Labels: 기능

#236 #225 feature: 프로필 관련 문제 해결
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/res/layout/fragment_change_phone.xml
  app/src/main/res/layout/fragment_profile_web.xml
  app/src/main/res/menu/menu_profile_web.xml
Labels: 버그, 기능

#234 [#230] [Feature] 필터 및 정렬 기능 구현
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FilterSort.kt
  app/src/main/res/layout/fragment_filter_sort.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_my.xml
  app/src/main/res/layout/row_study_all.xml
  app/src/main/res/layout/row_study_my.xml
Labels: 기능, UI

#237 [Feature] 전체 디자인 간격 및 크기 수정
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/CustomFindEmailDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FABBehavior.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
  app/src/main/res/layout/custom_dialog_find_email.xml
  app/src/main/res/layout/fragment_change_phone.xml
  app/src/main/res/layout/fragment_change_pw.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_find_email_auth.xml
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_step1.xml
  app/src/main/res/layout/fragment_join_step2.xml
  app/src/main/res/layout/fragment_join_step3.xml
  app/src/main/res/layout/fragment_other_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_search.xml
Labels: UI
