Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-08, with the labels that each got.

#273 [#269] feature 프래그먼트 바인딩 널 처리
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_join_step3.xml
Labels: 리팩터링

#275 #258 feature 프로필 및 수정 화면 UI 개선
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/SqlUserLinkData.kt
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileStudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ItemTouchHelperCallback.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ItemTouchHelperListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAddAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileStudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/res/drawable/keyboard_arrow_down_24px.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_study.xml
  app/src/main/res/layout/row_part_study.xml
  app/src/main/res/layout/row_profile_study.xml
Labels: 기능, UI

#279 [#272] bug 전화번호 인증 계정 중복 확인 기능 수정
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
Labels: 버그

#277 [#271] [Feature] 스터디 목록 사진 불러오기
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewHolder.kt
  app/src/main/res/anim/breathing_up_down.xml
  app/src/main/res/drawable/arrow_down_24px.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/row_study.xml
  app/src/main/res/values/colors.xml
Labels: 버그, 기능, UI, 리팩터링

#280 [Feat] #274 DB 연결 해제 코드 수정
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 기능

#282 [#281] bug 전화번호 계정 중복 확인 코드 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
Labels: 버그

#286 266 feature 글 수정 mysql 연결
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/SqlDetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt
Labels: 기능, 리팩터링

#290 [feature #287] 전에 사용하던 파일 연결 해제 및 삭제
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/repository/SqlDetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/VBBaseBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt
Labels: 리팩터링

#292 [Bug #291] 글 작성시 글 작성자 정보가 안담기는 현상 수정
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
Labels: 버그

#284 278 refactor 비밀번호 변경하기 리팩토링
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/HikariCPDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDao.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPasswordAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPasswordFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindUpdatePasswordFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPasswordViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneSocialFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePwFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePasswordViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePwViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/BottomNaviViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
  app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
  app/src/main/res/layout/custom_snackbar_with_icon.xml
  app/src/main/res/layout/fragment_change_password_auth.xml
  app/src/main/res/layout/fragment_change_password_email.xml
  app/src/main/res/layout/fragment_change_phone.xml
  app/src/main/res/layout/fragment_change_phone_auth.xml
  app/src/main/res/layout/fragment_change_phone_email.xml
  app/src/main/res/layout/fragment_change_phone_social.xml
  app/src/main/res/layout/fragment_change_pw.xml
  app/src/main/res/layout/fragment_find_email_auth.xml
  app/src/main/res/layout/fragment_find_password_auth.xml
Labels: 버그, 기능, UI, 리팩터링

#289 #276 feature: 프로필 화면 데이터베이스 연결 마무리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileStudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ItemTouchHelperCallback.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAddViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Interest.kt
  app/src/main/res/layout/row_link_add.xml
  app/src/main/res/layout/row_profile_study.xml
Labels: 기능

#288 [#285] feature 회원가입 기능 hilt 라이브러리 적용
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/adapter/JoinViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/HiltModule.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
  build.gradle.kts
Labels: 기능

#296 [#295] bug sns계정 회원가입 버그 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
Labels: 버그

#299 [#298] collectWhenStarted 함수 수정
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
Labels: 리팩터링

#304 [#294] [Fix] fab 및 바텀 내비 버튼 오류 개선
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatMessagesDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/StudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
  app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/repository/ChatMessagesRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/ChatRoomRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyListRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatMessagesViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatRoomViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePasswordEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneSocialFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePasswordViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FABBehavior.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/OnRecyclerViewScrollListener.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/layout/fragment_bottom_navi.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_group.xml
  app/src/main/res/layout/fragment_chat_oneto_one.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_my.xml
  app/src/main/res/layout/fragment_write.xml
Labels: 버그, 리팩터링

#307 [feature #303] 상세화면 좋아요 적용
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/SqlDetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt
Labels: 기능, 리팩터링

#313 [Feat] #309 sns 계정 회원가입 후 joinType 전달
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
Labels: 기능

#312 #302 feature: 프로필 화면 kotlin flow 적용
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileStudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: 기능, 리팩터링

#314 [#300] feature 회원가입 뷰페이저 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/res/layout/fragment_join.xml
Labels: 리팩터링

#316 [feature #310] 스터디 상세화면 이미지 상세보기 기능
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail_image_zoom.xml
Labels: 기능

#319 [#311] [Feature] 로그인 및 자동로그인 로딩 구현 및 UI 개선
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDao.kt
  app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
  app/src/main/java/kr/co/lion/modigm/model/UserData.kt
  app/src/main/java/kr/co/lion/modigm/model/UserLinkData.kt
  app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/WriteStudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/ProfileStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileStudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudySearchAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_other_login.xml
Labels: 기능, UI

#321 [#320] [Feature] 스터디 목록 스크롤 시 새로고침 기능
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FavoriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_study_all.xml
  app/src/main/res/layout/fragment_study_my.xml
  app/src/main/res/layout/study_item_shimmer_layout.xml
Labels: 버그, 기능, UI
