Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-07, with the labels that each got.

#244 [#240] feature 글쓰기 기능 datasource mysql로 변경
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/kr/co/lion/modigm/db/write/WriteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/write/WriteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/SqlStudyData.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/WriteStudyRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
Labels: 기능

#249 [feature #242] 글 상세화면 mysql연결
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/study/SqlRemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/SqlRemoteDetailDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/SqlUserData.kt
  app/src/main/java/kr/co/lion/modigm/repository/SqlDetailRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: 기능, 리팩터링

#254 [#253] feature 회원가입 기능 flow 적용
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep1ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 리팩터링

#257 #243: feature 프로필 화면 mysql 적용
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDataSource.kt
  app/src/main/java/kr/co/lion/modigm/model/SqlUserData.kt
  app/src/main/java/kr/co/lion/modigm/model/SqlUserLinkData.kt
  app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/InterestBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkAddViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/LinkViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/PartStudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ProfileViewModel.kt
  app/src/main/res/drawable/image_default_profile.png
Labels: 기능, 리팩터링

#256 [#255] feature 회원가입 후 userIdx를 sharedPreferences에 저장
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 기능

#261 [#252] [Feature] 로그인 기능 mysql 연동
  app/src/main/java/kr/co/lion/modigm/db/favorite/FavoriteListDao.kt
  app/src/main/java/kr/co/lion/modigm/db/favorite/FavoriteListDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/favorite/RemoteFavoriteDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/login/LoginDao.kt
  app/src/main/java/kr/co/lion/modigm/db/login/LoginDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/StudyDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/StudyDataSource.kt
  app/src/main/java/kr/co/lion/modigm/db/study/StudyListDao.kt
  app/src/main/java/kr/co/lion/modigm/db/study/StudyListDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/FavoriteRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt
  app/src/main/java/kr/co/lion/modigm/repository/StudyListRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/favorite/adapter/FavoriteAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/favorite/adapter/FavoriteViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/favorite/vm/FavoriteViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/CustomFindEmailDialog.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPwAuthFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/FindPwFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginError.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/ResetPwFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/SplashScreenActivity.kt
  app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FABBehavior.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FavoriteFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudySearchAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyViewHolder.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
  app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
  app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt
  app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: 기능, 리팩터링

#264 [Refactor] #262 회원가입기능 에러 처리 리팩토링
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
  app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
  app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
Labels: 리팩터링
