Repository APP-Android2/FinalProject-modigm, pull requests merged in 2024-10, with the labels that each got.

#389 [#382] feature 회원가입,탈퇴 텍스트뷰 사이즈 수정
  app/src/main/java/kr/co/lion/modigm/ui/profile/DeleteUserFragment.kt
  app/src/main/res/layout/fragment_delete_user.xml
  app/src/main/res/layout/fragment_join_step2.xml
  app/src/main/res/values/strings.xml
Labels: UI

#392 [#391] fix 회원탈퇴가 안되는 버그 수정
  app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt
Labels: 버그

#393 [#385] Fix 파이어베이스 인증 정보 삭제가 안되는 버그 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/vm/DeleteUserViewModel.kt
Labels: 버그

#390 [feature #388] 3차 테스트 피드백 수정
  app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
  app/src/main/java/kr/co/lion/modigm/model/NotificationData.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt
  app/src/main/java/kr/co/lion/modigm/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
  app/src/main/res/layout/custom_menu_item.xml
  app/src/main/res/layout/fragment_profile_web.xml
  app/src/main/res/layout/row_notification.xml
  app/src/main/res/menu/menu_profile_web.xml
Labels: 버그, UI

#397 [#396] feat 고객센터, 회원 신고, 스터디 신고에 연결되는 구글폼 추가 및 수정 작업
  app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
  app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
  app/src/main/java/kr/co/lion/modigm/util/Links.kt
Labels: 기능

#400 [#399] fix 이름 전화번호 입력화면 넘어가지는 부분 수정
  app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
Labels: 버그
